[tools]
go = "1.25.4"
trunk = "latest"
bun = "1.2.4"
node = "22.14.0"

[tasks]
"install:go" = "go mod download"
"install:bun" = "cd web && bun install"
install = { depends = ["install:*"] }

"codegen:gql" = "go run github.com/99designs/gqlgen && trunk fmt internal/graphql"
"codegen:relay" = "cd web && bun run relay && cd .. && trunk fmt web/src/__generated__"
codegen = { depends = ["codegen:gql", "codegen:relay"] }

"build:web" = { run = "cd web && bun run build", depends = ["codegen"] }
"build:go" = { run = "go build -o dist/fluxo ./cmd/fluxo", depends = [
  "codegen",
] }
build = { depends = ["build:web", "build:go"] }

lint = { run = "trunk check", depends = ["install", "codegen"] }
fmt = "trunk fmt"

"test:go" = { run = "go test ./...", depends = [
  "install",
  "codegen",
  "build:web",
] }
test = { depends = ["test:*"] }

ci = { depends = ["lint", "test"] }
