package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/cenkalti/rain/torrent"
	"github.com/lucasew/fluxo/internal/session"
)

// AddTorrent implements mutation resolver
func (r *mutationResolver) AddTorrent(ctx context.Context, input AddTorrentInput) (*Torrent, error) {
	opts := &torrent.AddTorrentOptions{}
	if input.Stopped != nil {
		opts.Stopped = *input.Stopped
	}
	if input.StopAfterDownload != nil {
		opts.StopAfterDownload = *input.StopAfterDownload
	}
	if input.StopAfterMetadata != nil {
		opts.StopAfterMetadata = *input.StopAfterMetadata
	}

	t, err := r.manager.AddTorrentFromInput(input.URI, input.TorrentData, opts)
	if err != nil {
		return nil, fmt.Errorf("adding torrent: %w", err)
	}

	return MapTorrent(t), nil
}

// RemoveTorrent implements mutation resolver
func (r *mutationResolver) RemoveTorrent(ctx context.Context, id string) (bool, error) {
	if err := r.manager.RemoveTorrent(id); err != nil {
		return false, err
	}
	return true, nil
}

// StartTorrent implements mutation resolver
func (r *mutationResolver) StartTorrent(ctx context.Context, id string) (bool, error) {
	if err := r.manager.StartTorrent(id); err != nil {
		return false, err
	}
	return true, nil
}

// StopTorrent implements mutation resolver
func (r *mutationResolver) StopTorrent(ctx context.Context, id string) (bool, error) {
	if err := r.manager.StopTorrent(id); err != nil {
		return false, err
	}
	return true, nil
}

// StartAllTorrents implements mutation resolver
func (r *mutationResolver) StartAllTorrents(ctx context.Context) (bool, error) {
	r.manager.StartAll()
	return true, nil
}

// StopAllTorrents implements mutation resolver
func (r *mutationResolver) StopAllTorrents(ctx context.Context) (bool, error) {
	r.manager.StopAll()
	return true, nil
}

// VerifyTorrent implements mutation resolver
func (r *mutationResolver) VerifyTorrent(ctx context.Context, id string) (bool, error) {
	if err := r.manager.VerifyTorrent(id); err != nil {
		return false, err
	}
	return true, nil
}

// AnnounceTorrent implements mutation resolver
func (r *mutationResolver) AnnounceTorrent(ctx context.Context, id string) (bool, error) {
	r.manager.AnnounceTorrent(id)
	return true, nil
}

// AddTracker implements mutation resolver
func (r *mutationResolver) AddTracker(ctx context.Context, id string, url string) (bool, error) {
	if err := r.manager.AddTracker(id, url); err != nil {
		return false, err
	}
	return true, nil
}

// AddPeer implements mutation resolver
func (r *mutationResolver) AddPeer(ctx context.Context, id string, addr string) (bool, error) {
	if err := r.manager.AddPeer(id, addr); err != nil {
		return false, err
	}
	return true, nil
}

// Torrents implements query resolver for torrents
func (r *queryResolver) Torrents(ctx context.Context) ([]*Torrent, error) {
	torrents := r.manager.GetTorrents()
	result := make([]*Torrent, len(torrents))
	for i, t := range torrents {
		result[i] = MapTorrent(t)
	}
	return result, nil
}

// Torrent implements query resolver for single torrent
func (r *queryResolver) Torrent(ctx context.Context, id string) (*Torrent, error) {
	t, err := r.manager.GetTorrent(id)
	if err != nil {
		return nil, fmt.Errorf("torrent not found: %w", err)
	}
	return MapTorrent(t), nil
}

// SessionStats implements query resolver for session stats
func (r *queryResolver) SessionStats(ctx context.Context) (*SessionStats, error) {
	stats := r.manager.GetStats()
	return MapSessionStats(&stats), nil
}

// TorrentPeers implements query resolver for torrent peers
func (r *queryResolver) TorrentPeers(ctx context.Context, id string) ([]*Peer, error) {
	peers, err := r.manager.GetPeers(id)
	if err != nil {
		return nil, fmt.Errorf("getting peers: %w", err)
	}
	return MapPeers(peers), nil
}

// TorrentAdded implements subscription resolver
func (r *subscriptionResolver) TorrentAdded(ctx context.Context) (<-chan *Torrent, error) {
	subID, eventChan := r.manager.EventBus().Subscribe()
	out := make(chan *Torrent)

	go func() {
		defer r.manager.EventBus().Unsubscribe(subID)
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-eventChan:
				if !ok {
					return
				}
				if event.Type == session.EventTorrentAdded && event.Torrent != nil {
					select {
					case out <- MapTorrent(event.Torrent):
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return out, nil
}

// TorrentRemoved implements subscription resolver
func (r *subscriptionResolver) TorrentRemoved(ctx context.Context) (<-chan string, error) {
	subID, eventChan := r.manager.EventBus().Subscribe()
	out := make(chan string)

	go func() {
		defer r.manager.EventBus().Unsubscribe(subID)
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-eventChan:
				if !ok {
					return
				}
				if event.Type == session.EventTorrentRemoved {
					select {
					case out <- event.ID:
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return out, nil
}

// TorrentUpdated implements subscription resolver
func (r *subscriptionResolver) TorrentUpdated(ctx context.Context, id *string) (<-chan *Torrent, error) {
	subID, eventChan := r.manager.EventBus().Subscribe()
	out := make(chan *Torrent)

	go func() {
		defer r.manager.EventBus().Unsubscribe(subID)
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-eventChan:
				if !ok {
					return
				}
				if event.Type == session.EventTorrentUpdated && event.Torrent != nil {
					// Filter by ID if specified
					if id != nil && event.Torrent.ID() != *id {
						continue
					}

					select {
					case out <- MapTorrent(event.Torrent):
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return out, nil
}

// StatsUpdated implements subscription resolver
func (r *subscriptionResolver) StatsUpdated(ctx context.Context) (<-chan *SessionStats, error) {
	subID, eventChan := r.manager.EventBus().Subscribe()
	out := make(chan *SessionStats)

	go func() {
		defer r.manager.EventBus().Unsubscribe(subID)
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-eventChan:
				if !ok {
					return
				}
				if event.Type == session.EventStatsUpdated && event.Stats != nil {
					select {
					case out <- MapSessionStats(event.Stats):
					case <-ctx.Done():
						return
					}
				}
			}
		}
	}()

	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
