package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"

	"github.com/cenkalti/rain/torrent"
	"github.com/lucasew/fluxo/internal/session"
)

// AddTorrent implements mutation resolver
func (r *mutationResolver) AddTorrent(ctx context.Context, input AddTorrentInput) (*Torrent, error) {
	opts := &torrent.AddTorrentOptions{}
	if input.Stopped != nil {
		opts.Stopped = *input.Stopped
	}
	if input.StopAfterDownload != nil {
		opts.StopAfterDownload = *input.StopAfterDownload
	}
	if input.StopAfterMetadata != nil {
		opts.StopAfterMetadata = *input.StopAfterMetadata
	}

	t, err := r.manager.AddTorrent(input.URI, opts)
	if err != nil {
		return nil, fmt.Errorf("adding torrent: %w", err)
	}

	return MapTorrent(t), nil
}

// okBool maps a manager error into the GraphQL (bool, error) mutation shape.
func okBool(err error) (bool, error) {
	if err != nil {
		return false, err
	}
	return true, nil
}

// RemoveTorrent implements mutation resolver
func (r *mutationResolver) RemoveTorrent(ctx context.Context, id string) (bool, error) {
	return okBool(r.manager.RemoveTorrent(id))
}

// StartTorrent implements mutation resolver
func (r *mutationResolver) StartTorrent(ctx context.Context, id string) (bool, error) {
	return okBool(r.manager.StartTorrent(id))
}

// StopTorrent implements mutation resolver
func (r *mutationResolver) StopTorrent(ctx context.Context, id string) (bool, error) {
	return okBool(r.manager.StopTorrent(id))
}

// StartAllTorrents implements mutation resolver
func (r *mutationResolver) StartAllTorrents(ctx context.Context) (bool, error) {
	r.manager.StartAll()
	return true, nil
}

// StopAllTorrents implements mutation resolver
func (r *mutationResolver) StopAllTorrents(ctx context.Context) (bool, error) {
	r.manager.StopAll()
	return true, nil
}

// VerifyTorrent implements mutation resolver
func (r *mutationResolver) VerifyTorrent(ctx context.Context, id string) (bool, error) {
	return okBool(r.manager.VerifyTorrent(id))
}

// AnnounceTorrent implements mutation resolver
func (r *mutationResolver) AnnounceTorrent(ctx context.Context, id string) (bool, error) {
	// Manager.AnnounceTorrent is a no-op when the id is missing; match other
	// mutations and surface not-found instead of returning a false success.
	if _, err := r.manager.GetTorrent(id); err != nil {
		return false, err
	}
	r.manager.AnnounceTorrent(id)
	return true, nil
}

// AddTracker implements mutation resolver
func (r *mutationResolver) AddTracker(ctx context.Context, id string, url string) (bool, error) {
	return okBool(r.manager.AddTracker(id, url))
}

// AddPeer implements mutation resolver
func (r *mutationResolver) AddPeer(ctx context.Context, id string, addr string) (bool, error) {
	return okBool(r.manager.AddPeer(id, addr))
}

// Torrents implements query resolver for torrents
func (r *queryResolver) Torrents(ctx context.Context) ([]*Torrent, error) {
	torrents := r.manager.GetTorrents()
	result := make([]*Torrent, len(torrents))
	for i, t := range torrents {
		result[i] = MapTorrent(t)
	}
	return result, nil
}

// Torrent implements query resolver for single torrent
func (r *queryResolver) Torrent(ctx context.Context, id string) (*Torrent, error) {
	t, err := r.manager.GetTorrent(id)
	if err != nil {
		// GetTorrent already wraps ErrTorrentNotFound; do not double-prefix.
		return nil, err
	}
	return MapTorrent(t), nil
}

// SessionStats implements query resolver for session stats
func (r *queryResolver) SessionStats(ctx context.Context) (*SessionStats, error) {
	stats := r.manager.GetStats()
	return MapSessionStats(&stats), nil
}

// TorrentPeers implements query resolver for torrent peers
func (r *queryResolver) TorrentPeers(ctx context.Context, id string) ([]*Peer, error) {
	peers, err := r.manager.GetPeers(id)
	if err != nil {
		// GetPeers already wraps ErrTorrentNotFound; do not double-prefix.
		return nil, err
	}
	return MapPeers(peers), nil
}

// subOutBuffer absorbs brief GraphQL client stalls. When full, sendSub drops the
// oldest value so this goroutine keeps draining the EventBus channel — a blocked
// send would fill the bus buffer and drop unrelated events (e.g. torrent_removed).
const subOutBuffer = 16

// sendSub delivers v without blocking on a slow consumer. Returns false when
// ctx is already cancelled and the caller should exit. If the buffer is full,
// the oldest value is dropped so this goroutine can keep draining EventBus.
func sendSub[T any](ctx context.Context, out chan T, v T) bool {
	if ctx.Err() != nil {
		return false
	}
	select {
	case out <- v:
		return true
	default:
	}
	// Drop oldest to make room (same freshness preference as EventBus.Publish).
	select {
	case <-out:
	default:
	}
	if ctx.Err() != nil {
		return false
	}
	select {
	case out <- v:
	default:
		// Still full (racing with another send or consumer); skip this value.
	}
	return true
}

// subscribeFilter wires EventBus → buffered out channel. match returns
// (value, true) to emit an event and false to skip. The out channel is closed
// when ctx is cancelled or the bus subscription ends.
func subscribeFilter[T any](
	ctx context.Context,
	bus *session.EventBus,
	match func(session.Event) (T, bool),
) <-chan T {
	subID, eventChan := bus.Subscribe()
	out := make(chan T, subOutBuffer)

	go func() {
		defer bus.Unsubscribe(subID)
		defer close(out)

		for {
			select {
			case <-ctx.Done():
				return
			case event, ok := <-eventChan:
				if !ok {
					return
				}
				v, ok := match(event)
				if !ok {
					continue
				}
				if !sendSub(ctx, out, v) {
					return
				}
			}
		}
	}()

	return out
}

// TorrentAdded implements subscription resolver
func (r *subscriptionResolver) TorrentAdded(ctx context.Context) (<-chan *Torrent, error) {
	return subscribeFilter(ctx, r.manager.EventBus(), func(event session.Event) (*Torrent, bool) {
		if event.Type != session.EventTorrentAdded || event.Torrent == nil {
			return nil, false
		}
		return MapTorrent(event.Torrent), true
	}), nil
}

// TorrentRemoved implements subscription resolver
func (r *subscriptionResolver) TorrentRemoved(ctx context.Context) (<-chan string, error) {
	return subscribeFilter(ctx, r.manager.EventBus(), func(event session.Event) (string, bool) {
		if event.Type != session.EventTorrentRemoved {
			return "", false
		}
		return event.ID, true
	}), nil
}

// TorrentUpdated implements subscription resolver
func (r *subscriptionResolver) TorrentUpdated(ctx context.Context, id *string) (<-chan *Torrent, error) {
	return subscribeFilter(ctx, r.manager.EventBus(), func(event session.Event) (*Torrent, bool) {
		if event.Type != session.EventTorrentUpdated || event.Torrent == nil {
			return nil, false
		}
		if id != nil && event.Torrent.ID() != *id {
			return nil, false
		}
		return MapTorrent(event.Torrent), true
	}), nil
}

// StatsUpdated implements subscription resolver
func (r *subscriptionResolver) StatsUpdated(ctx context.Context) (<-chan *SessionStats, error) {
	return subscribeFilter(ctx, r.manager.EventBus(), func(event session.Event) (*SessionStats, bool) {
		if event.Type != session.EventStatsUpdated || event.Stats == nil {
			return nil, false
		}
		return MapSessionStats(event.Stats), true
	}), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
